module.exports = {
  buttonNodes: "[data-nodes='true']",
  buttonList: "[data-list='true']",
  searchComponent: "[data-search-component='true']",
  pagination: "[data-pagination='true']",
  input: "[data-input='true']",
  buttonSearch: "[data-button-search='true']",
  buttonClear: "[data-button-clear='true']",
  buttonNewCustomer: "[data-test-selector='new-customer-button']",
  editCustomer: "tbody>tr>td>div>svg:nth-child(1)",
  viewCustomer: "tbody>tr>td>div>svg:nth-child(2)",
  editFieldCountry: "[data-edit-country='true']",
  editButtonSubmit: "[data-button-submit='true']",
  editedCountry: "div>table>tbody>tr>td:nth-child(3)",
  deleteButton: "tbody>tr>td:nth-child(6)>button",
  buttonCreateNewCustomer: "[data-button-submit='true']",
  grabText: "[data-uuid='true']",
};
